["pyproject.toml".tool.poetry.group.test.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
pytest-xdist = {extras = ["psutil"], version = "^3.5.0"}
pytest-sugar = "^0.9.7"
Faker = "^20.1.0"
pytest-snapshot = "^0.9.0"

["pyproject.toml".tool.pytest.ini_options]
testpaths = [
  "tests",
]
python_files = "test*.py"
addopts = "-rsxX -l --tb=short --strict-markers --doctest-modules"
xfail_strict = "true"
